language: go
go:
  - 1.4.3
  - 1.5.4
  - 1.6.4
  - 1.7.4
  - tip

services:
  - memcache
  - redis-server

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/acc2c57482e94b44f557
    on_success: change
    on_failure: always
    on_start: false
