version: '2'
services: 

  blog-db:
    build: 
      context: ./db
    container_name: blog-db
    stdin_open: true
    tty: true
    volumes:
      - blog-data:/blog-data


  blog-router:
    build:
      context: ./router
    container_name: blog-router
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    environment:
      - GIN_MODE=release
    volumes:
      - blog-data:/blog-data


  blog-fbcomments:
    build: 
      context: ./plugins/fbcomments
    container_name: blog-fbcomments
    stdin_open: true
    tty: true


  blog-legacy:
    build:
      context: ./legacy
    container_name: blog-legacy
    stdin_open: true
    tty: true
    volumes:
      - blog-data:/blog-data


volumes:
  blog-data:
    driver: local
