version: '2'
services: 
  
  blog-db:
    build: 
      context: ./db
    container_name: blog-db
    stdin_open: true
    tty: true
    volumes:
      - blog-data:/blog-data

  redis-cli:
    image: redis:3.2.9-alpine
    container_name: blog-redis-cli
    stdin_open: true
    tty: true
    # attach then `redis-cli -h blog-db`
    command: ash

  blog-router:
    build:
      context: .
      dockerfile: router.Dockerfile
    container_name: blog-router
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    environment: # PROD
      - GIN_MODE=release # PROD
    volumes:
      - blog-data:/blog-data
      # when using these lines, installInitialData should be commented
      # in router/main.go
      # - ./themes/laurel/templates:/blog-data/templates # DEV
      # - ./themes/laurel/static:/blog-data/static/theme # DEV
      # - ./themes/laurel/config.json:/blog-data/theme/config.json # DEV

  blog-fbcomments:
    build: 
      context: ./plugins/fbcomments
    container_name: blog-fbcomments
    stdin_open: true
    tty: true

  blog-legacy:
    build:
      context: ./legacy
    container_name: blog-legacy
    stdin_open: true
    tty: true
    volumes:
      - blog-data:/blog-data

volumes:
  blog-data:
    driver: local
