version: '2'
services: 
  
  blog-db:
    build: 
      context: ./db
    container_name: blog-db
    stdin_open: true
    tty: true
    volumes:
      # - blog-data:/blog-data # PROD
      - ./sample/db:/blog-data/db # DEV

  redis-cli:
    image: redis:3.2.9-alpine
    container_name: blog-redis-cli
    stdin_open: true
    tty: true
    # attach then `redis-cli -h blog-db`
    command: ash

  blog-router:
    build:
      context: .
      dockerfile: router.Dockerfile
    container_name: blog-router
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    # environment: # PROD
    #   - GIN_MODE=release # PROD
    volumes:
      # - blog-data:/blog-data # PROD
      - ./sample/themes:/blog-data/themes # DEV
      - ./sample/config.json:/blog-data/config.json # DEV
      - ./sample/files:/blog-data/files # DEV
      - ./router/initial-data/admin:/blog-data/admin # DEV
      - ./router/initial-data/js:/blog-data/js # DEV
      - ./router/initial-data/robots.txt:/blog-data/robots.txt # DEV
      - ./go/src:/go/src # DEV
    command: ash # DEV

  blog-fbcomments:
    build: 
      context: ./plugins/fbcomments
    container_name: blog-fbcomments
    stdin_open: true
    tty: true

  blog-legacy:
    build:
      context: ./legacy
    container_name: blog-legacy
    stdin_open: true
    tty: true
    volumes:
      - blog-data:/blog-data

volumes:
  blog-data:
    driver: local
